# Site settings
title: Drive Constructor
email: info@driveconstructor.com
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.driveconstructor.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
