pump:
  title: Pumps 
fan:
  title: Fans 
conveyor:
  title: Conveyor 
extruder:
  title: Extruder 
wind:
  title: Wind turbine
tidal:
  title: TBD 
winch:
  title: TBD 
kiln:
  title: TBD 
stirrer:
  title: TBD 
elevator:
  title: TBD 
compressor:
  title: TBD 
ship:
  title: TBD 
