pump:
  title: Pumps
  text: Systems for driving pumps
fan:
  title: Fans 
conveyor:
  title: Conveyor 
extruder:
  title: Extruder 
wind:
  title: Wind turbine
tidal:
  title: Tidal turbine 
winch:
  title: Winch 
kiln:
  title: Kiln 
stirrer:
  title: Stirrer 
elevator:
  title: Elevator 
compressor:
  title: Compressor 
ship:
  title: Ship 
